CREATE TABLE STORE_GENRE(
  -- colName dataType optionalConstrains
  GENRE_ID NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE STORE_BOOK(
  BOOK_ID NUMBER(10) PRIMARY KEY,
  ISBN VARCHAR2(10) UNIQUE NOT NULL,
  TITLE VARCHAR2(256) NOT NULL,
  PRICE NUMBER(6, 2) NOT NULL,
  GENRE NUMBER(10),
  CONSTRAINT FK_BOOK_GENRE FOREIGN KEY(GENRE)
  REFERENCES STORE_GENRE(GENRE_ID)
);

CREATE TABLE STORE_AUTHOR(
  AUTHOR_ID NUMBER(10) PRIMARY KEY,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50),
  BIO VARCHAR2(1000)
);

--JUNCTION TABLE - HAS COMPOSITE PK, BOTH COLUMNS ARE FK 
CREATE TABLE STORE_BOOK_AUTHOR(
  BOOK_ID NUMBER(10),
  AUTHOR_ID NUMBER(10),
  PRIMARY KEY (BOOK_ID, AUTHOR_ID),
  FOREIGN KEY (BOOK_ID) REFERENCES STORE_BOOK(BOOK_ID),
  FOREIGN KEY(AUTHOR_ID) REFERENCES STORE_AUTHOR(AUTHOR_ID)
);