-------------------------CHINOOK HOMEWORK----------------------------

--2. SQL QUERIES--

  --2.1-SELECT--

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';

SELECT * FROM EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;

  --2.2-ORDER BY--

SELECT * FROM ALBUM
ORDER BY TITLE DESC;

SELECT FIRSTNAME FROM CUSTOMER
ORDER BY CITY;  --NOTE: ASCENDING IS BY DEFAULT

  --2.3-INSERT INTO--

SELECT * FROM GENRE;

INSERT INTO GENRE
VALUES(26,'ALTERNATIVE ROCK');

INSERT INTO GENRE
VALUES( 27,'LATIN');

CREATE SEQUENCE GENSEQ;

CREATE OR REPLACE TRIGGER GEN_TRIGGER 
   BEFORE INSERT ON GENRE 
   FOR EACH ROW 
   BEGIN
      
      SELECT GENSEQ.NEXTVAL
      INTO :NEW.GENREID
      FROM DUAL;
   END;
/
SELECT* FROM EMPLOYEE;
INSERT INTO EMPLOYEE
VALUES(10, 'Smith','Andy','Sales Support Agent', 2, '07-JAN-81', '28-MAY-19','23-13 Junction Road', 'Los Angeles','CA', 'United States','90710','1 (213) 877-2332', '1 (213) 223-2111', 'smithandy1@chinookcorp.com');

SELECT * FROM CUSTOMER;

CREATE SEQUENCE CUSTSEQ;

CREATE OR REPLACE TRIGGER CUST_TRIGGER 
   BEFORE INSERT ON CUSTOMER 
   FOR EACH ROW 
   BEGIN
      
      SELECT CUSTSEQ.NEXTVAL
      INTO :NEW.CUSTOMERID
      FROM DUAL;
   END;
/

INSERT INTO CUSTOMER
VALUES(60,'FRANK','SINATRA','BANAMEX','AVENIDA CENTRAL S.V','MEXICO CITY',NULL,'MEXICO','3134', '+52 (223) 324-4424',NULL,'FRANKS1@HOTMAIL.COM', NULL);

  --2.4 UPDATE--

SELECT * FROM CUSTOMER
WHERE FIRSTNAME = 'Aaron';

UPDATE CUSTOMER
SET FIRSTNAME = 'Robert', LASTNAME = 'Walter'
WHERE CUSTOMERID = 32;

SELECT * FROM ARTIST
WHERE NAME LIKE 'C%';

UPDATE ARTIST
SET NAME = 'CCR'
WHERE ARTISTID = 76;

  --2.5 LIKE--
SELECT * FROM INVOICE
WHERE BILLINGADDRESS LIKE 'T%';

  --2.6 BETWEEN--
SELECT TOTAL
FROM INVOICE
WHERE TOTAL BETWEEN 15 AND 50;

SELECT HIREDATE
FROM EMPLOYEE
WHERE HIREDATE BETWEEN '01-AUG-02' AND '01-MAR-04';

  --2.7 DELETE--
  
DELETE FROM CUSTOMER WHERE FIRSTNAME = 'Robert'and LASTNAME= 'Walter';

select * from invoice where customerid =32;

DELETE FROM INVOICE WHERE CUSTOMERID = 32;

DELETE FROM INVOICELINE WHERE INVOICEID = 290;

--3. SQL FUNCTION--
