--DROP TABLE BANK_ACCOUNT;

CREATE TABLE BANK_USER(
USER_ID NUMBER(10) PRIMARY KEY,
F_NAME VARCHAR2(100) NOT NULL,
L_NAME VARCHAR2(100) NOT NULL,
USERNAME VARCHAR2(100) NOT NULL UNIQUE,
PWD VARCHAR2(100) NOT NULL
);


CREATE TABLE BANK_ACCOUNT(
ACCOUNT_NUM NUMBER(10) PRIMARY KEY,
BALANCE NUMBER(10, 2) NOT NULL,
ACCOUNT_TYPE VARCHAR2(100) NOT NULL,
CUSTOMER_ID NUMBER(10),
FOREIGN KEY (CUSTOMER_ID) REFERENCES BANK_USER (USER_ID)
);



select * from BANK_USER;
select * from BANK_ACCOUNT;




CREATE SEQUENCE USER_SEQ;

CREATE SEQUENCE ACCOUNT_SEQ;


Insert into bank_user values (user_seq.nextVal, 'Nick', 'F', 'nf', 'pass');
Insert into bank_account values (5, 1000000, 'checking', 5);
